csv: train_labels.csv
data_directory: dataset
epochs: 30
fold_type: 'StratifiedKFold'
freeze_cnn: true
grayscale: true
input_channels: 1
input_size: 256
k_fold: 5
last_checkpoint: null
learning_rate: 0.0001
learning_rate_meta: 0.0001
lr_max: 0.1
lr_step: 5
meta_features:
- pct
model_type: efficientnet-b0
mri_types:
- FLAIR
- T1w
- T1wCE
- T2w
num_classes: 2
num_images_seq: -1
num_workers: 0
optimizer_type: Adam
optimizer_weight_decay: 0.0005
pin_memory: true
sample_format: .dcm  # .png
save_directory: models\experiments\
schedule_type: StepLR
seed: 42
seq_type: T2w
step_size: 2
test_batch_size: 1
test_directory: dataset\test\
test_drop_last: false
test_shuffle: false
train_batch_size: 8
train_directory: dataset\train\
train_drop_last: true
train_shuffle: true
train_val_size: 0.2
transform: false
type: train
